# docker-compose setup for a development environment.
# To use this file, populate config-docker.env with the following:
#
# MYSQL_PASSWORD - a password for the mysql user
# MYSQL_ROOT_PASSWORD - a password for the mysql *root* user
#
# Then you can run:
#   - docker-compose build
#   - docker-compose up

version: '3.5'

services:
  app:
    build: ./
    restart: always
    ports:
      - "8000:3031"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      APP_DB_NAME: agagd
      AGAGD_USER: agagd
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      SECRET_KEY: insecure-key-for-testing
      DEBUG: "true"
      LOAD_FIXTURES: "true"
    volumes:
      - ./agagd/agagd:/srv/agagd
      - ./agagd/agagd_core:/srv/agagd_core
      - ./agagd/media:/srv/media
      - ./agagd/static:/srv/static
      - ./agagd/templates:/srv/templates

  db:
    build:
      context: ./
      dockerfile: Dockerfile.mysql
    restart: always
    volumes:
      - database:/var/lib/mysql
    environment:
      # this is safer than it looks, since without a 'ports' section, docker-compose
      # isolates this app to a network local to this compose file.
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: agagd
      MYSQL_DATABASE: agagd
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

volumes:
  database:
